### ISSUE TITLE
TypeError: Item in __all__ must be str, not function

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/ccos-scripts#105]
## Description
Many Python files in the repo use the `__all__` array to limit exported objects. Every item in the list should be a string containing the names of the exported variables.

Currently the variable contains the variables themselves instead of their names, like this.
```python
def set_labels(*args):
    pass

__all__ = [set_labels]
```
Instead the correct way which would be this.
```diff
- __all__ = [set_labels]
+ __all__ = ["set_labels"]
```

## Reproduction

1. Try wildcard importing from any such file. 
```python
from set_labels import *
```
2. See error.
```
TypeError: Item in set_labels.__all__ must be str, not function
```

## Expectation
Wildcard imports, while discouraged, should still work.

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by shubhanshu02** [comment]
Hi @dhruvkb! Can I help to solve this issue?
