### ISSUE TITLE
Import Error for log.py

### ISSUE THREAD

**Issue by rajdesai24** [creativecommons/ccos-scripts#110]
Module log.py is directly imported from normalize_repos module in normalize_repos.py which causes an import error while running the script. 
<img width="1224" alt="Screenshot 2020-12-05 at 4 03 42 AM" src="https://user-images.githubusercontent.com/53701807/101222276-741a7600-36af-11eb-9a90-408fc9758e1c.png">

<img width="1224" alt="Screenshot 2020-12-05 at 4 10 25 AM" src="https://user-images.githubusercontent.com/53701807/101222467-d1162c00-36af-11eb-94ad-221bfdc34e9e.png">

**Comment by dhruvkb** [comment]
@rajdesai24 this is not an error as when the scripts are executed, the `normalize_repos/` directory is treated as the working directory. 
https://github.com/creativecommons/ccos-scripts/blob/75e141a83d4096aec42d3391c036523520c65456/.github/workflows/normalize_repos.yml#L22

You can get rid of the error/warning by configuring your IDE (which appears to be PyCharm) to treat the directory as "Sources Root".
![Screenshot 2020-12-05 at 7 10 49 PM](https://user-images.githubusercontent.com/16580576/101244623-97840600-372d-11eb-81fd-07df142d502d.png)

**Comment by dhruvkb** [comment]
@rajdesai24 please update the issue if the above solution works for you.

**Comment by rajdesai24** [comment]
I'll try this and let you know asap
