### ISSUE TITLE
Use GitHub Workflow commands for better logs

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/ccos-scripts#112]
## Problem
Our logger uses explicit ANSI color coding for log states like success, warning and error but does not use the GitHub notation making the (extremely verbose) logs less navigable and harder to review when debugging.

## Description
GitHub Workflows have some special notations for different outputs that lead to different presentation of those outputs in the UI. They are documented in the [GitHub docs](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions).

Notable notations include the ones for [DEBUG](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-a-debug-message), [WARNING](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-a-warning-message) and [ERROR](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-error-message) messages:
```
::debug::{message}
::warning file={name},line={line},col={col}::{message}
::error file={name},line={line},col={col}::{message}
```

Configuring the customised logger to output messages in this format can improve the logging system drastically in terms of readability and improve debugging experience.

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by shubhanshu02** [comment]
Hi @dhruvkb! I want to work on this issue. 
I tried searching for the logging module and found that the `IndentFormatter` class in `normalize_repos/log.py` has the colour coding for the logs. Is this the module we want to edit in this issue?

**Comment by dhruvkb** [comment]
Yes @shubhanshu02, that's the module.

**Comment by shubhanshu02** [comment]
@dhruvkb, the workflow commands are working fine as per the below format, but the `** **`, used to make the function name bold, is not working as expected (I think markdown isn't used in this case). What should I do now?
`::levelname:: time  | indent function(bold) |  messages`

The following is the output as per GitHub Actions on manual trigger in my fork.
![image](https://user-images.githubusercontent.com/54344426/102064047-d5171c00-3e1c-11eb-8bbf-d1ea0d5592b6.png)
