### ISSUE TITLE
Add "awaiting triage" label

### ISSUE THREAD

**Issue by akmadian** [creativecommons/ccos-scripts#17]
## Problem Description

When doing issue triage, it's hard to tell the difference between issues that have not been triaged, and as such, are marked as `not ready for work`, and issues that have been triaged, but actually are not ready for work.

## Solution Description

We could add an `awaiting triage` label as default to issue templates. 

## Alternatives

We could use `blocked` for what we're currently using `not ready for work` for, but an `awaiting triage` label would be much more specific.

**Comment by kgodey** [comment]
That sounds good to me. We'll need to add the label here and then update the issue templates in the following repos:
https://github.com/creativecommons/.github
https://github.com/creativecommons/cccatalog

**Comment by krysal** [comment]
I can work on this @kgodey @akmadian, what exactly its need to be done on this repo? I guess that in the others two, labels of `.github/ISSUE_TEMPLATEs/*.md` should be modified, am I right?

**Comment by achilep** [comment]
hello are you still working on it? if not i will like to work on it.

**Comment by akmadian** [comment]
@achilep it seems like @krysal got to it first, you can find other issues to work on [here](https://github.com/search?q=org%3Acreativecommons+is%3Aissue+is%3Aopen+label%3A%22help+wanted%22) :)

@krysal, you'll need to add the label to `./normalize_repos/labels.py`, then create an issue in [creativecommons/.github](https://github.com/creativecommons/.github) to update the default issue template, and an issue in [creativecommons/cccatalog](https://github.com/creativecommons/cccatalog) to update that repo's issue template. Hopefully that answers your questions, if not, let Kriti or I know!

**Comment by krysal** [comment]
Thanks @akmadian! working on it.

**Comment by achilep** [comment]
No problem @akmadian and @krysal

**Comment by krysal** [comment]
Tasks done @akmadian, waiting for review on #21 (@kgodey).
creativecommons/.github#5
creativecommons/cccatalog#329

Now you can work on one of those @achilep, are good first issues.
