### ISSUE TITLE
Create GitHub workflow to automatically put community PRs on CC Search repos in the correct project

### ISSUE THREAD

**Issue by kgodey** [creativecommons/ccos-scripts#23]
## Problem Description
Pull requests from the community (anyone other than CC staff) on CC Search related repos need to be moved to the "In Progress (Community)" column in the [Active Sprint – CC Search](https://github.com/orgs/creativecommons/projects/7) project.

## Solution Description
We need to create a GitHub workflow in this repo that runs every hour and checks for PRs on the CC Search related repositories that don't have an associated project (PRs by CC staff are automatically moved by a separate GitHub workflow that's already deployed). We need to move these PRs into the correct project and column.

## Additional context
- CC Search related repos are: 
    - https://github.com/creativecommons/cccatalog
    - https://github.com/creativecommons/cccatalog-api
    - https://github.com/creativecommons/cccatalog-frontend
- [GitHub Actions documentation](https://help.github.com/en/actions)
- [Project automation workflow example on cccatalog-frontend](https://github.com/creativecommons/cccatalog-frontend/blob/develop/.github/workflows/project-automation.yml)
- Discussion about why the project automation workflow above doesn't work for community PRs: https://github.com/creativecommons/cccatalog-api/issues/456

**Comment by subhamX** [comment]
I would like to work on this. Can you please assign this to me?

**Comment by kgodey** [comment]
@subhamX per our new [contribution guidelines](https://opensource.creativecommons.org/contributing-code/), we are no longer assigning things to people if they are marked "help wanted", anyone is welcome to send a PR without permission.

**Comment by RachealN** [comment]
I am taking up this issue too

**Comment by subhamX** [comment]
Oh! Sorry for my last comment, I wasn't aware of it. 

Anyhow, I searched for actions in the marketplace which satisfies the above requirements but wasn't able to find one. Should I build a new  GitHub Action using JavaScript using GitHub APIs, which first fetch all pull requests that are created an hour ago and then update the Project Dashboard.

**Comment by taran1515** [comment]
But for updating the Project Dashboard, you need to check if the pull request has been made by  member outside the organization.

Is there any way to get it using Github Action?
I couldn't find one.

**Comment by kgodey** [comment]
You don't need to check whether the pull request has been made by someone outside the organization, PRs made by people in the organization will automatically be moved to the correct project. You just need to make sure that the PR does not already have a project associated with it.

@subhamX sure, that would be fine.

**Comment by subhamX** [comment]
Hey @kgodey, Sorry for referencing this issue multiple time, in my initial commits the added workflow wasn't triggering on the actions dashboard that's why I pushing the code multiple times. It was a silly mistake from my side as I had changed the Cron Expression and also the credentials were invalid. Anyhow, I have created the GitHub action with the above functionality. Took a lot of time to test my action especially for non-community members after creating a test organisation. Request you to please review my PR.
