### ISSUE TITLE
Vocabulary repo tasks are inconsistently named

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/ccos-scripts#26]
## Describe the bug
The unit test task in Vocabulary is named `test`, and a functionally identical task in Vue Vocabulary is named `unit`.

## Expected behavior
Two tasks that performs the same function should be named the same for consistency. The name `unit` for unit tests seems to be a good one.

**Comment by dhruvkb** [comment]
@kgodey these task names are not correct:
![Screen Shot 2020-04-07 at 01 31 50](https://user-images.githubusercontent.com/16580576/78599992-bb760b80-786f-11ea-8f07-e234da98a62b.png)

You might want to revert this PR and reopen the issue.

**Comment by sp35** [comment]
@kgodey This needs to be closed!

**Comment by kgodey** [comment]
@sp35 it is closed.
