### ISSUE TITLE
Add Community PR action shows error when PR is in project

### ISSUE THREAD

**Issue by kgodey** [creativecommons/ccos-scripts#29]
## Problem Description
The "add community PR" workflow shows an error when a PR is already in a project e.g.

`Error while adding Pull Request Card To Column [Project already has the associated issue]`

(See: https://github.com/creativecommons/ccos-scripts/runs/552801037?check_suite_focus=true)

## Solution Description
PRs that are already in a Project should not be added to a project at all, and so there should be no error.

**Comment by kgodey** [comment]
@subhamX would you be able to work on this?

**Comment by subhamX** [comment]
Hi @kgodey , thank you for pointing this issue and giving this opportunity to me. I will ensure that in case the PR is already linked with the Project then nothing is printed on the console. I will update the release as soon as possible.

**Comment by subhamX** [comment]
@kgodey I have fixed the issue and have updated the release tag.

**Comment by kgodey** [comment]
looks good, @subhamX! thank you! :)
