### ISSUE TITLE
Issue with Git push permissions in generate project pages script

### ISSUE THREAD

**Issue by kgodey** [creativecommons/ccos-scripts#30]
## Problem Description
The `git push` action in the Generate Project Pages action is not working because of authentication issues. The `push` command from `GitPython` does not use the credentials supplied earlier in the file.

See https://github.com/creativecommons/ccos-scripts/runs/550457801?check_suite_focus=true for example.

## Solution Description
`origin.push()` should use the credentials that the repo was initialized with earlier in the file.

## Additional context

[GitPython documentation](https://gitpython.readthedocs.io/en/stable/)

**Comment by kgodey** [comment]
@sp35 are you interested in working on this?

**Comment by sp35** [comment]
@kgodey Interested!

**Comment by kgodey** [comment]
@sp35 thank you!

**Comment by sp35** [comment]
@kgodey Although, it's obvious that it's lacking credentials at https://github.com/creativecommons/ccos-scripts/runs/550457801?check_suite_focus=true

However, I couldn't replicate it, when testing on my fork https://github.com/sp35/creativecommons.github.io-source/commits/master

Possibly we can try the equivalent of 
```git push --repo <GITHUB_REPO_URL_WITH_CREDENTIALS>```

maybe ```repo.git.push(repo=GITHUB_REPO_URL_WITH_CREDENTIALS)```

**Comment by sp35** [comment]
@kgodey Please check if there is an issue with the secret ADMIN_GITHUB_TOKEN. Was the token changed recently and unchanged in the secrets of this repository?

I tested it against the fork of my repo and I was able to push after setting up the secret.

Please do let me know if the problem persists.

**Comment by kgodey** [comment]
@sp35 what permissions did you use when you set up your secret?

**Comment by sp35** [comment]
Access to public repo only.

FYI I had to skip the part where we collect data from all repositories of CC as I was testing on my fork (my name isn't an org), which is justified as there was an issue with the push command, which worked!

**Comment by kgodey** [comment]
I've verified that the token has access to push to all public and private repos. It's also the same token used for the normalize repos script, which updates repo information fine (and that's working correctly).

**Comment by kgodey** [comment]
There is still an authentication error: https://github.com/creativecommons/ccos-scripts/actions/runs/72019007

**Comment by sp35** [comment]
This wasn't expected. I'll look into it.

**Comment by sp35** [comment]
Just a single change, i.e. the organization, the code works. https://github.com/sp35/ccos-scripts/commit/e2d148d03bb289a15bc384f5833aa9677e502765

Tests ok - https://github.com/sp35/ccos-scripts/runs/568573407?check_suite_focus=true

Pushed commit - https://github.com/sp35/creativecommons.github.io-source/commit/43473392f3571633a4a99be365213569a679cd33?diff=split

Sad that I still couldn't figure it out, but it's all about git now.
Why is ```git push <URL_with_token> master``` giving error 128, auth failed, if @kgodey has confirmed that there isn't an issue with the pat/secret; given it works on my fork?

The best I could do was to bring the problem to the git level from the gitpython one; which brings in the questions, is push actually allowed, what's interfering?

**Comment by kgodey** [comment]
That's very odd. I'll do some tests with the token when I have some time.

**Comment by kgodey** [comment]
It appears I had the wrong token set up, updating the token seemed to fix it. I am still not sure _why_ the token didn't work, but I'll worry about that if it comes up again.

**Comment by sp35** [comment]
> @kgodey Please check if there is an issue with the secret ADMIN_GITHUB_TOKEN.
The first thing that I had suspected!
Ended up looking at a lot of similar errors but learned something, so nvm!

**Comment by kgodey** [comment]
Yeah, I had tried switching the token then and nothing changed. :(
