### ISSUE TITLE
Assign repo_data correctly to get empty slack keys

### ISSUE THREAD

**Issue by sp35** [creativecommons/ccos-scripts#44]
[Generate Project Page Script](https://github.com/creativecommons/ccos-scripts/blob/65bf97cd2916cdc56a94465354d4350223c71586/generate_projects_page/generate_projects_page.py#L132)

This isn't actually an issue as it's fine to not have an empty slack key but the assignment made is meaningless, hence a reordering would be needed.

**Comment by kgodey** [comment]
Thanks!
