### ISSUE TITLE
Set up GitHub Actions to run the normalize repos script every day

### ISSUE THREAD

**Issue by kgodey** [creativecommons/ccos-scripts#5]
## Problem Description
The normalize repos script is only run manually currently. We want it to automatically run so that our GitHub repos are always up to date with the latest labels and settings.

## Solution Description
Set up a GitHub Actions workflow in this repo to run the script every day.

## Additional context
- [GitHub Actions documentation](https://help.github.com/en/actions)
- Please include instructions on how to set up the appropriate GitHub Token. Your GitHub token will not have permissions to update any repo settings so you'll need to test using repos on your own account.

**Comment by AyanChoudhary** [comment]
My PRs are completed and have their reviews pending. So can I take this while I await the reviews?

**Comment by kgodey** [comment]
Yes, go ahead.
