### ISSUE TITLE
Add an 'accessibility' label for frontend repos

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/ccos-scripts#52]
## Problem
We need an `accessibility` label for the following repos:
- Vocabulary
- Vue Vocabulary
- Fonts
- CC Catalog API
- CC Open Source

There might be more repos that need it.

## Description
Tickets related to accessibility can be tagged with this label for ease-of-classification.

## Alternatives
I'd prefer a label like `aspect:a11y` for consistency with the labelling scheme in Vocabulary repos but that would not fit in with the other repos in the list.

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by dhruvkb** [comment]
**Update:** CC Catalog API already an accessibility label.

This is related to creativecommons/vocabulary#454 and creativecommons/vocabulary#455. Tagging @AyanChoudhary, the original reporter of these issues.

**Comment by kgodey** [comment]
Let's just use `accessibility` for consistency, and let's implement it for all repos.

**Comment by rohitgeddam** [comment]
Can i add the accessibility labels on them.

**Comment by dhruvkb** [comment]
@kgodey I think we should put this issue in `blocked` until the new labels spec is finalised.

**Comment by kgodey** [comment]
Agreed, we are making larger label changes.

**Comment by kgodey** [comment]
We're not going to be doing this any more, we have a new set of standard labels that will soon be documented.
