### ISSUE TITLE
Add meta label?

### ISSUE THREAD

**Issue by akmadian** [creativecommons/ccos-scripts#7]
## Problem Description

Adding a label in the [normalize_repos](https://github.com/creativecommons/ccos-scripts/tree/master/normalize_repos) script for issues that are meant to track a meta discussion or larger goal rather than a specific issue or feature, or an issue representing a large task that's meant to track several smaller tasks. I don't think there's any label that quite covers this exactly.

I'm not sure if "meta" is quite the right word for this, although I think it could work.

## Alternatives

We could widen the scope of an existing label, but I don't think that any of the existing labels' descriptions would really work for this purpose if widened.

I could do this, but it would also be a quick and easy opportunity for outside contributors.

**Comment by AyanChoudhary** [comment]
This looks like something I can do along with writing the workflow(which I am doing currently). So can I take it?

**Comment by kgodey** [comment]
I'd rather let someone else work on it to give more people an opportunity to contribute.

I think `meta` is fine.

**Comment by keshav2212** [comment]
I want to work on this. Can I take this?
