### ISSUE TITLE
Exempt non-engineering repos from branch protection normalisation

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/ccos-scripts#76]
## Problem
Non-engineering repos, identified by `engineering_project` set to `false` in the [CC metadata file](https://opensource.creativecommons.org/contributing-code/github-repo-guidelines/#cc-metadata-file) present in each repo should not be subjected to branch protection normalisation in the [`normalize_repos`](https://github.com/creativecommons/ccos-scripts/blob/master/normalize_repos/normalize_repos.py) workflow.

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by sukhdeepg** [comment]
@kgodey I want to work on this issue, if ok, please assign this to me. Can you also please share information about the `ADMIN_GITHUB_TOKEN` and in what way will I be needing it for contribution?

**Comment by dhruvkb** [comment]
@sukhdeepg the `ADMIN_GITHUB_TOKEN` is a [personal access token from GitHub](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) used for authentication against the GitHub API. It gives the client access to make changes to the repository settings.

**Comment by sukhdeepg** [comment]
@dhruvkb Got it! Thank you.

**Comment by sukhdeepg** [comment]
@dhruvkb I've made a pull request. Please review it.
