### ISSUE TITLE
Switch all CC Open Source automation to using a bot token

### ISSUE THREAD

**Issue by kgodey** [creativecommons/ccos-scripts#78]
I need to set up a second account with admin permissions and 2FA to use for CC Open Source automation. Currently, automation is performed using my token and it's not clear what I do and what happens automatically.

Thanks to @dhruvkb for raising this.

**Comment by zackkrida** [comment]
hm, did kriti or kriti-bot open this ticket? 🤔 🤖

**Comment by kgodey** [comment]
This should be done.
