### ISSUE TITLE
Update README in /normalize_repos with new script name

### ISSUE THREAD

**Issue by AyanChoudhary** [creativecommons/ccos-scripts#8]
## Describe the bug
The instructions in README mention standardize_label.py whereas the correct script name is normalize_repos.py

**Comment by kgodey** [comment]
Thanks for catching this!

**Comment by cristomathew** [comment]
is it still open?

**Comment by pavitra14** [comment]
I would like to solve this issue if no one is doing it :)

**Comment by cristomathew** [comment]
It's solved if I am not wrong.

**Comment by kgodey** [comment]
It is not yet solved, go ahead @pavitra14. This is for the README inside the folder, not the main project README.
