### ISSUE TITLE
Failing workflow for pushing issues to CC open Source

### ISSUE THREAD

**Issue by avats-dev** [creativecommons/ccos-scripts#82]
## Description

[Push issues to CC Open Source](https://github.com/creativecommons/ccos-scripts/blob/master/.github/workflows/push_issues_to_ccos.yml) workflow is failing since last 8 days (maybe more).

## Reproduction

Go [here](https://github.com/creativecommons/ccos-scripts/actions?page=8&query=workflow%3A%22Push+issues+to+CC+Open+Source%22)

## Screenshots

![Screenshot from 2020-09-23 01-23-04](https://user-images.githubusercontent.com/35889327/93930671-5a69c380-fd3b-11ea-92e0-0cc872e10e78.png)

## Additional context

Somewhat related to #81 
**Error seems to be `authentication failure` in both cases.**

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by kgodey** [comment]
There's some sort of issue with the token, I need to debug it since it's my token.

**Comment by kgodey** [comment]
I regenerated the token, which fixed this.
