### ISSUE TITLE
Account for case differences when syncing labels

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/ccos-scripts#84]
## Description
While Python does not see the label "hacktoberfest" and "Hacktoberfest" as equal, GitHub does. So if there is a case difference, the script will try to create the label and GitHub will raise an error that it already exists.

https://github.com/creativecommons/ccos-scripts/blob/7d7ee1d332473ad34028231cf77035a23f318972/normalize_repos/models.py#L106

## Reproduction

1. Change the case of a standard label.
2. Sync workflow will fail.
3. See error.

## Expectation
Python should be able to [sync the names](https://pygithub.readthedocs.io/en/latest/github_objects/Label.html#github.Label.Label.edit) to their correct values, while accounting for different cases when matching labels to the JSON file.

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by wescran** [comment]
Hello, I am interested in taking on this task!

**Comment by kgodey** [comment]
go ahead @wescran

**Comment by tushar912** [comment]
@wescran are u working on this. If not can i take it up?

**Comment by dhruvkb** [comment]
@tushar912 please allow a 7 day buffer period of inactivity before considering an issue as inactive. In the meantime, might I suggest our [Issue Finder](https://opensource.creativecommons.org/contributing-code/issue-finder/)?

**Comment by tushar912** [comment]
Ok

**Comment by wescran** [comment]
Hi there, I will have a `[WIP]` PR opened today!

**Comment by wescran** [comment]
PR is ready for review!
