### ISSUE TITLE
Increase readability of label data files

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/ccos-scripts#85]
## Problem
Both `labels.json` and `skills.json` are not very readable for the following reasons:

- both are JSON files, which are not very readable for humans.
- currently the `labels.json` file uses emoji as unicode glyphs, which look like two codepoints in a string. It's not possible to identify the emojis from the text.

## Description
GitHub allows using ["colon-style markup"](https://docs.github.com/en/rest/reference/issues#update-a-label) instead of native emoji. We should use that as the value of the emoji key. Additionally YAML would be a much better option for files that are manually read or written.

## Alternatives
The current implementation works. Not working on the issue is the alternative.

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by JuanVqz** [comment]
Hello! Should I change the JSON file to Yaml file? I can do it if you allow me.
For emojis, should be like the following line?

emoji: ”: strawberry:”

**Comment by dhruvkb** [comment]
Yes @JuanVqz, please change the JSON files to YAML and the emojis to their corresponding `:xyz:` representation as in this [cheat sheet](https://www.webfx.com/tools/emoji-cheat-sheet/).

**Comment by JuanVqz** [comment]
sorry I haven't experience with python and I didn't see I need to do something with it, otherwise, I didn't take it.
  can I fix the .yml files to finish this?

**Comment by dhruvkb** [comment]
Yeah okay, just make sure the JSON and YML files are in sync and I'll make the remaining Python changes.
