### ISSUE TITLE
Remove Hacktoberfest labels

### ISSUE THREAD

**Issue by nimishbongale** [creativecommons/ccos-scripts#97]
## Description
Now that Hacktoberfest is all done and dusted with, we can go ahead and remove the Hacktoberfest labels. We'll also have to run the necessary scripts with admin rights in order to remove labels attached with the existing Hacktoberfest issues.

I can go ahead and remove the Hacktoberfest associated labels from the `labels.json` file as suggested by @dhruvkb.

## Expectation
1. Hacktoberfest associated labels should be removed.
2. Hacktoberfest labels that are attached with existing issues must also be removed.
3. We could potentially replace them with "help wanted" labels as well, but I'm really not sure about this.

## Resolution

- [x] I would be interested in resolving this issue.

**Comment by dhruvkb** [comment]
@nimishbongale I think you should this issue as well as PR #98, based on [this comment (and it's upvotes)](https://github.com/creativecommons/ccos-scripts/pull/98#issuecomment-722478061).

**Comment by nimishbongale** [comment]
> @nimishbongale I think you should this issue as well as PR #98, based on [this comment (and it's upvotes)](https://github.com/creativecommons/ccos-scripts/pull/98#issuecomment-722478061).

Closing this issue!
